project:
  type: book
  output-dir: docs

book:
  title: "The openair book"
  subtitle: "A Guide to the Analysis of Air Pollution Data"
  author: "David C Carslaw and Jack Davison"
  date: today
  date-format: long
  repo-url: https://github.com/davidcarslaw/openair-book/
  repo-branch: master
  repo-actions: [edit]
  favicon: "favicon.png"
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - intro.qmd
    - openair-package.qmd
    - part: "Data Access"
      chapters:
        - UK-air-quality-data.qmd
        - access-met-data.qmd
    - part: "Directional Analysis"
      chapters:
        - wind-roses.qmd
        - polar-freq.qmd
        - percentile-roses.qmd
        - polar-plots.qmd
        - polar-annulus.qmd
        - trajectory-analysis.qmd
    - part: "Time Series and Trends"
      chapters:
        - time-plot.qmd
        - time-variation.qmd
        - time-proportion.qmd
        - trend-level.qmd
        - calendar-plot.qmd
        - theil-sen.qmd
        - smooth-trend.qmd
    - part: "Model Evaluation"
      chapters:
        - mod-stats.qmd
        - taylor-diagram.qmd
        - conditional-quantiles.qmd
    - part: "Interactive Maps"
      chapters:
        - maps-overview.qmd
        - maps-network.qmd
        - maps-polar.qmd
        - maps-traj.qmd
    - part: "Utility functions"
      chapters:
        - utility-functions.qmd
        - scatter-plot.qmd
    - references.qmd
  appendices:
   - appendix-annotate.qmd
   - appendix-hysplit.qmd
   - appendix-trends.qmd

bibliography: [DCC-refs.bib, packages.bib]

execute: 
  warning: false
  message: false
  echo: true
  error: false
  eval: true
  prompt: false
  freeze: auto
  cache: true

format:
  html:
    theme: lumen
    highlight-style: pygments
    fig-align: center
    code-link: true
    code-copy: true
    link-external-newwindow: true
    citation-location: margin
    css: style.css
    
editor_options: 
  chunk_output_type: console