project:
  type: book
  output-dir: docs

book:
  title: "The openair book"
  subtitle: "A Guide to the Analysis of Air Pollution Data"
  author: 
  - David C Carslaw
  - Jack Davison
  date: today
  date-format: long
  site-url: "https://bookdown.org/david_carslaw/openair/"
  repo-url: https://github.com/davidcarslaw/openair-book/
  repo-branch: master
  repo-actions: [edit]
  favicon: "favicon.png"
  sharing: [twitter, facebook, linkedin]
  sidebar: 
    search: true
    logo: images/plume.png
  chapters:
    - index.qmd
    - sections/intro/intro.qmd
    - sections/intro/openair-package.qmd
    - part: "Data Access"
      chapters:
        - sections/data-access/UK-air-quality-data.qmd
        - sections/data-access/access-met-data.qmd
    - part: "Directional Analysis"
      chapters:
        - sections/directional-analysis/wind-roses.qmd
        - sections/directional-analysis/polar-freq.qmd
        - sections/directional-analysis/percentile-roses.qmd
        - sections/directional-analysis/polar-plots.qmd
        - sections/directional-analysis/polar-annulus.qmd
        - sections/directional-analysis/trajectory-analysis.qmd
    - part: "Time Series and Trends"
      chapters:
        - sections/trend-analysis/time-plot.qmd
        - sections/trend-analysis/time-variation.qmd
        - sections/trend-analysis/time-proportion.qmd
        - sections/trend-analysis/trend-level.qmd
        - sections/trend-analysis/calendar-plot.qmd
        - sections/trend-analysis/theil-sen.qmd
        - sections/trend-analysis/smooth-trend.qmd
    - part: "Model Evaluation"
      chapters:
        - sections/model-evaluation/mod-stats.qmd
        - sections/model-evaluation/taylor-diagram.qmd
        - sections/model-evaluation/conditional-quantiles.qmd
    - part: "Interactive Maps"
      chapters:
        - sections/maps/maps-overview.qmd
        - sections/maps/maps-network.qmd
        - sections/maps/maps-polar.qmd
        - sections/maps/maps-traj.qmd
    - part: "Utility functions"
      chapters:
        - sections/utilities/utility-functions.qmd
        - sections/utilities/scatter-plot.qmd
    - sections/references.qmd
  appendices:
   - sections/appendices/appendix-annotate.qmd
   - sections/appendices/appendix-hysplit.qmd
   - sections/appendices/appendix-trends.qmd
   - sections/appendices/appendix-gethelp.qmd

bibliography: [DCC-refs.bib, packages.bib]
csl: atmospheric-environment.csl

execute: 
  warning: false
  message: false
  echo: true
  error: false
  eval: true
  prompt: false
  freeze: auto
  cache: true

format:
  html:
    theme: lumen
    highlight-style: pygments
    fig-align: center
    code-link: true
    code-copy: true
    link-external-newwindow: true
    citation-location: margin
    css: style.css
    
editor_options: 
  chunk_output_type: console