---
editor_options: 
  markdown: 
    wrap: 72
---

# Introduction {#sec-intro}

This document provides information on the use of R to analyse air
pollution data. The document supports an initiative to develop and make
available a consistent set of tools for analysing and understanding air
pollution data in a free, open-source environment.

The amount of monitoring data available is substantial and increasing.
In the UK alone there are thought to be over 1000 continuous monitoring
sites. Much of the data available is only briefly analysed; perhaps with
the aim of comparing pollutant concentrations with national and
international air quality limits. However, as it will hopefully be seen,
the critical analysis of air pollution data can be highly rewarding,
perhaps yielding important information on pollutant sources that was
previously unknown or unquantified.

While many of the options in these functions allow quite a sophisticated
analysis to be undertaken, the defaults generally use the simplest (and
fastest) assumptions. A more detailed analysis can refine these
assumptions e.g. by accounting for autocorrelation, or fine-control over
the appearance of a plot.

It should be noted that while the aim is to keep this documentation up
to date, the primary source of information related to the different
functions is contained within the package itself. Once loaded, type
`?openair` to see all the help pages associated with the package. The
website for [openair]{.pkg} is
<https://davidcarslaw.github.io/openair/>.

::: callout-tip
## Note!

The next Section contains important information on loading the
[openair]{.pkg} package for the first time and the input data
requirements. Users will need to consider the advice in this section to
ensure that [openair]{.pkg} can be used without problems.}
:::

